### ISSUE TITLE
Not familiar with framework

### ISSUE THREAD

**Issue by hrace009** [magenik/perfect-world-webplatform#1]
hi,

Thank for a great work, but i am not familiar with php Framework.
i use apache or ngix as my webserver.
on this Laravel, i seen so many directory.
![capture](https://cloud.githubusercontent.com/assets/7691118/7390284/ace2da7a-eea0-11e4-855a-223ea6ff1170.JPG)

witch directory that i should use as Public DocumentRoot for my webserver? 
Thank you.

**Comment by mb-afk** [comment]
the goal of the framework is to make life easier, and laravel is not the exception. You can run "php artisan serve" to use the built-in server and if you want to use your own web server then the document root should be the public folder

**Comment by hrace009** [comment]
okay, thanks for the information
